#!/usr/bin/env bash

# Credit to ThePrimeagen
# https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/Projects -maxdepth 3 -mindepth 3 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

dirname=$(basename "$selected" | sed 's/\./_/g')

tmux switch-client -t =$dirname

if [[ $? -eq 0 ]]; then
    exit 0
fi

tmux new-session -c $selected -d -s $dirname && tmux switch-client -t $dirname || tmux new -c $selected -A -s $dirname

echo tmux
